### ISSUE TITLE
The Hordes incompat [1.19.2]

### ISSUE THREAD

**Issue by Allomere** [wendall911/BetterDays#21]
When Better Days is installed the hordes from The Hordes do not trigger naturally.

I have set day/night_speed to 50 on Better Days's config (to speed the testing of this issue)
On The Hordes's config i have set hordes spawn on first day to "true" and hordeSpawnDays to 1 (to make the hordes spawn every day).

The hordes have a "dayLength" config for when a mod changes the duration of the day/night cycle, but i dont think that should be a issue, because until now every mod that relies on day duration have worked correctly with **Better Days** without changing the day length on their configs (ex:serene seasons).

Im sorry if this issue is not beeing caused by better days, if its not i will take the issue to The Hordes's

_Thank you for making this mod, you added multiple features in to a single "package" that would normally need 3/5+ mods to work, and runs really well with other mods._

**Comment by wendall911** [comment]
I'll take a look tomorrow and see if it is an issue with BetterDays. Yeah, you shouldn't have to change anything with the day length. Thanks for reporting.

**Comment by wendall911** [comment]
@Allomere Can you please let me know what minecraft version you are seeing this issue?

**Comment by wendall911** [comment]
It's odd, looking at the code for The Hordes, it should work just fine. I'm not doing anything with ticking, so it should be fine, but will debug as soon as I can identify the version.

**Comment by wendall911** [comment]
@Allomere Oh, nm, I see in the description! Oops, will take a look soon.

**Comment by wendall911** [comment]
Ok, I see the issue. It is a little complex, but essentially there is this setting: hordeEventByPlayerTime that needs to be set to false for everything to work. The reason is that if it is set to true, it uses the time played data for logged in players. This doesn't get de/incremented based on time speed, and that's not something I'm willing to change, as it probably breaks other stuff. So if you change the hordeEventByPlayerTime setting, hordes will spawn, but use the actual gametime.

When I changed this on a running world, I had to run /hordes spawnWave {player} 1 to get hordes to trigger at midnight again. I'm not sure if it is necessary. You'll  need to test a bit.

**Comment by wendall911** [comment]
@Allomere let me know if you have any issues changing that setting. I don't have any other creative workarounds given the implementation.

**Comment by Allomere** [comment]
Thank you so much, im so sorry for making you look in to this issue when it was just a setting on someone else's mod.
But thank you for looking in to it anyways, you are a legend

**Comment by wendall911** [comment]
@Allomere No worries looking into it. It did make me think about maybe doing some stuff differently to support this kind of use-case, but I worry that I'd break other things. I think The Hordes could fix this by adding custom data to keep track of player time (which is arguably what they should be doing) and it would work well with that setting. I think it is an oversight on their part. Would be worth filing a bug report and referencing this issue if you need that specific feature.
